//created on: 2015-11-6
package drl.zdrygl.message

//list any import classes here.
import java.lang.String
import java.util.Map
import com.founder.drools.core.model.RuleBean
import org.apache.commons.httpclient.NameValuePair

//declare any global variables here

rule "Your First Rule"

    when
        ruleBean:RuleBean(ruleName == 'LGSQ');
    then    	
		Map resMap=ruleBean.executeServiceByHttp("getZdrylx","zdrygllx=01");
		
		if("success".equals(resMap.get("status"))){
			ruleBean.setResStatus(0);
			String resStr=(String)resMap.get("resStr");
        	ruleBean.setResponse(resStr+"列管申请");
        }
        else
        	ruleBean.setResponse(resMap.get("errorMessage"));
end
